### ISSUE TITLE
Question: Correct version in module

### ISSUE THREAD

**Issue by ZiggyQubert** [zkteco-home/RedisJson#3]
Thanks for the work on this.

Is it possible for the redisJson module to report the correct version, when running `module list` it reports `ver: 999999`
```
> module list
1) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) (integer) 999999
   5) "path"
   6) "rejson.dll"
   7) "args"
   8) (empty array)
```
instead of its actual version - 2.4.6 I'm guessing

**Comment by zkteco-home** [comment]
version updated,thanks
